apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com:coopdloop/how-to-use-fluxcd.git
  secretRef:
    name: example-app-2-github
